configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-steep-shadow-a5zpsdij.us-east-2.aws.neon.tech/neondb?user=godbeast9999&password=C9fjMHczmst5
  - configuration:
      name: auth_config
      client_id: 047682746fd743b6b953dae6670557a3
      client_secret: e5b4fb97aaf445d5b0160e92fdbe6829
